### ISSUE TITLE
R 3.3.1 version

### ISSUE THREAD

**Issue by bgruening** [conda-forge/r-base-feedstock#2]
Would it be possible to also get a R 3.3.1 version with a higher build number than in the `r` channel? This old in in the R channel has problems with plotting and breaks a lot of things.

@johanneskoester @lecorguille

**Comment by johanneskoester** [comment]
I doubt that his would help bioconda, because the conda-forge channel has a lower build number in our current setup. Even if it would help, it would mean that the we would have to adjust all the patches that are used here, and try to not make the mistakes that caused the broken stuff in the R channel version of 3.3.1. At least for me, that would mean too much work at the moment for a version that will become obsolete once the R port to conda-forge is finished. Of course, I am completely open to PRs in this direction.

**Comment by johanneskoester** [comment]
Finally, the different underlying library versions between conda-forge and R could introduce incompatibilities between the R packages from the R channel (that we would still use) and the potentially fixed r-base from here.

**Comment by johanneskoester** [comment]
This is yet another reminder how super urgent the port of all the packages from the r channel is. I am in the final stages to fix building r packages on conda-forge/staged-recipes, see conda-forge/staged-recipes#2098. If that PR is merged, adding the other packages should be straightforward. Currently the last error in that PR only occurs on windows. Maybe I'll just skip windows to speed everything up... I"m not interested in it anyways.

**Comment by bgruening** [comment]
I'm not talking strictly about bioconda. The latest version of `r` 3.3.1 is broken and I don't think it is good to keep these version and don't offer a workaround. 
For bioconda, we actually would need to rebuild everything against 3.3.2, which again is a major undertaking :(

**Comment by johanneskoester** [comment]
I agree, but why is it not fixed in the R channel? Regarding R 3.3.2, does that mean you would be in favor of having R 3.3.1 in conda-forge and not R 3.3.2 at all? When I started, I thought we would move to 3.3.2 at some point and therefore considered it worthless to first support 3.3.1 at a point where it was already outdated...

**Comment by bgruening** [comment]
The R channel is not really responsive. They created R 3.3.2 and that was it - and thats the fix :(
We should go for 3.3.2, this is completely fine, but I think we should not leave 3.3.1 broken. But I see your point, maybe this is the wrong repository. I should complain more in the r-channel :(
