### ISSUE TITLE
ETA for Windows r-base > 4.1.3?

### ISSUE THREAD

**Issue by abalter** [conda-forge/r-base-feedstock#248]
### Comment:

Linux an osx are up-to-date with v4.3. Is there a problem with updating the Windows version at this time?

**Comment by jakirkham** [comment]
Perhaps this provides additional context on the issues encountered there

https://github.com/conda-forge/r-base-feedstock/pull/205#issuecomment-1107911434

**Comment by abalter** [comment]
Thanks @jakirkham . I was super surprised this morning to learn from a colleague trying to update our Windows server that conda-forge's version is so out of date. I wonder if anyone is going to return to it---the version is now two minor versions behind, and heading into one year!

**Comment by jakirkham** [comment]
As noted in the linked issue, the ask involves modernizing Windows toolchain. This is a non-trivial effort. That said, help would definitely be welcome. Though completely understand if that's not something you want to commit too

**Comment by h-vetinari** [comment]
> if there were a clear statement of the problem, that would be a great starting point.

See https://github.com/conda-forge/conda-forge.github.io/issues/1654 & https://github.com/conda-forge/conda-forge.github.io/issues/1044. It's a very tricky problem, but people are looking at it (got discussed in the most recent core meeting, see [minutes](https://github.com/conda-forge/conda-forge.github.io/blob/main/src/orga/minutes/2023-05-03.md)).

**Comment by jakirkham** [comment]
Yeah sorry it has been a very busy week. Was meaning to update this thread after the core meeting.

As mentioned, this is a tricky problem. Though I really appreciate your patience and thoughtfulness (especially given this was not obvious from the surface)

Anyways raised it with the core team this week to see how we might best move this forward. We essentially discussed what funding options we might have, whether we had any one interested in doing this work, what the scope might be, etc.

The good news is it looks like Anaconda is also interested in a path forward on these issues

That said, no idea on timeline at this point, since we are still trying to figure out some of the basics, which would determine that

**Comment by scdub** [comment]
> Anyways raised it with the core team this week to see how we might best move this forward. We essentially discussed what funding options we might have, whether we had any one interested in doing this work, what the scope might be, etc.

@jakirkham did these discussions progress any further? I help support a small team who contributes to R support for ArcGIS, and we'd love to see more modern R versions available via conda-forge. If there are resources needed, I can bring this up with the team if they are identified. I imagine that the number of people with the specific intersection of skills for the UCRT work is small making this particularly challenging.

**Comment by isuruf** [comment]
I'll add list of things to do to the top comment at https://github.com/conda-forge/conda-forge.github.io/issues/1654.
If you can help with those, then we can make progress. Cannot make any promises though.

**Comment by joshualeond** [comment]
Curious how this is progressing as well? Thanks!

**Comment by isuruf** [comment]
R 4.3 builds are there

**Comment by jakirkham** [comment]
Thanks Isuru! 🙏

Truly impressive work getting this shipped! 🥳
