### ISSUE TITLE
Run export for r-base

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/r-base-feedstock#284]
### Comment:

The recipe linter produces the following warning when adding r-base as a host dependency:

*"If r-base is a host requirement, it should be a run requirement."*

Shouldn't r-base rather have a `run_export` section instead of having this requirement?

This would also take care of having a proper lower bound for the version that was found at build time in the host environment.

**Comment by wolfv** [comment]
I am actually also curious about this. I expected some run exports. I also think with the `noarch` run export we can have an expressive enough set of run exports for the r-base package, no?

**Comment by jdblischak** [comment]
It's my understanding that this requirement applies to both `python` and `r-base` in order to support `noarch` recipes, which can't have any version constraints

* [conda-forge docs on `noarch` recipes](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-builds)
* [PR that added `r-base` to be linted the same as `python` in regards to `noarch` recipes](https://github.com/conda-forge/conda-smithy/pull/1219)
* [Current conda-smithy linting code that enforces this](https://github.com/conda-forge/conda-smithy/blob/1845745da9f0650eca2750c2ba8991fd89048489/conda_smithy/lint_recipe.py#L587)

**Comment by wolfv** [comment]
@jdblischak we can add two different run exports:

- weak: r-base Major.Minor
- noarch: r-base

Then, noarch packages will depend on `r-base` without version, and arch'd packages will depend on `r-base >=X.X,<X.Y`.

Would _that_ make sense?

**Comment by isuruf** [comment]
It should be `r-base Major.Minor` for both.

**Comment by wolfv** [comment]
Thank you :)

**Comment by jdblischak** [comment]
I knew about "weak" versus "strong" run exports. The "noarch" run exports is new to me. Where is this documented?

* The conda recipe [docs](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#export-runtime-requirements) on run exports only mention "weak" versus "strong"
* The conda-forge [docs](https://conda-forge.org/docs/maintainer/pinning_deps/#specifying-run_exports) on run exports doesn't mention the different kinds at all. And the section on [noarch recipes](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-builds) also doesn't mention it

**Comment by wolfv** [comment]
It's probably not well documented. `noarch` run exports are applied to noarch packages.
