### ISSUE TITLE
r-base requires non-existing version of msys-conda-epoch which causes dependency conflicts

### ISSUE THREAD

**Issue by joelostblom** [conda-forge/r-base-feedstock#351]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

When trying to install an environment with one of the python packages vegafusion or vl-convert-python together with r-base I run into a conflict for the package `msys2-conda-epoch`. It seems like since `r-base` requires this package to be `<0.0a0` whereas `vegafusion` requires `[20160418 |>=20160418 ]`:

![Image](https://github.com/user-attachments/assets/db106809-d010-4607-98c4-b1306ba552d1)

Looking up the [msys-conda-epoch](https://anaconda.org/conda-forge/msys2-conda-epoch/files) package shows only a single version which is the one vegafusion references, so I'm not sure what it means that `r-base` requires a version that doesn't exist in the msys repo. This has only been and issue since version 4.2 of `r-base` and 4.1 installs fine. On linux this install just fine, so it is just this msys Windows package that seems to be the issue.

Here is an env file to reproduce. I tried with mamba too and I see the same issue. My `conda` version is 24.7.1.

```yaml
name: 'py311r42vf'
channels:
    - conda-forge
    - r
    - defaults
dependencies:
    - python=3.11
    - vegafusion
    - r-base>=4.2

```

### Installed packages

None since the env cant be installed

### Environment info

None since the env cant be installed

**Comment by mfansler** [comment]
All R 4.2+ Windows builds have switched to using UCRT and so other packages need to rebuild for this. [The migrator status page](https://conda-forge.org/status/migration/?name=r-base44_and_m2w64-ucrt) indicates that `vegafusion-python-embed` is waiting on [`cargo-bundle-licenses` to rebuild](https://github.com/conda-forge/cargo-bundle-licenses-feedstock/pull/19), and then it will rebuild. Until then, `vegafusion-python-embed` is only compatible with R 4.1 and lower as you have found.

Otherwise, impossible-to-satisfy constraints are an idiom for excluding co-installation. Namely, the `libgcc` that `r-base` is linked against should not be co-installed with `m2w64-gcc-libs`, and `msys2-conda-epoch` is a metapackage that provides an umbrella term for that and all its derivatives.

**Comment by joelostblom** [comment]
Thanks for the explanation! I left a comment in that PR and will follow it for updates.
